server:
  port: 8010
spring:
  application:
    name: scdemo4-consumer-movie-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #表示将自己的IP注册到EurekaServer，false则用hostname注册
    prefer-ip-address: true